### ISSUE TITLE
js functionality after modal renders

### ISSUE THREAD

**Issue by yaboyanees** [dei79/jquery-modal-rails#2]
I have a multi step form that I call into a modal box using link_to_modal. It renders properly but i loose the functionality. For example, on the regular form page, I am able to click an option and the next step flies in, until the last step is chosen and the form submits. When I open it up in the modal box, I click the first step and it never goes to the second step. Its like frozen or something? Please help. I cant figure out why the form works regular and not in the modal box?

**Comment by dei79** [comment]
Yes this will not happen automatically so you need to build your own AJAX calls in the dialog. I'm open if you have good ideas to make a standard feature which supports wizard mode.

**Comment by yaboyanees** [comment]
Sounds good. My multistep form is a user quiz. I will look into making those Ajax calls. I'm assuming I make a partial.js file and put all the calls in there?

-Anees

**Comment by dei79** [comment]
I'm happy to integrate your pull request. Will close this thread because the pull request will open a new issue
